[package]
name = "Khalidi"
version = "0.0.0"

[addresses]
NamedAddr = "0xCAFE"

[dependencies]
MoveStdlib = { local = "/home/walker/Stackup_Move_Campaign/move/language/move-stdlib", addr_subst = { "std" = "0x1" } }
